---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ceph-nvmeof-gateway
  # TODO(warning): multiple references to "openshift-storage"
  namespace: openshift-storage
---
# ssc based on the Ceph-CSI ssc
# the "users:" contains a reference to the "openshift-storage" namespace
#
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: "ceph-nvmeof"
# To allow running privilegedContainers
allowPrivilegedContainer: true
# CSI daemonset pod needs hostnetworking
allowHostNetwork: true
priority:
# SYS_ADMIN is needed for rbd to execute rbd map command
allowedCapabilities:
  - "SYS_ADMIN"
# Needed as we run liveness container on daemonset pods
allowHostPorts: true
# Set to false as we write to RootFilesystem inside container
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - ALL
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
# The type of volumes which are mounted to csi pods
volumes:
  - configMap
  - projected
  - emptyDir
  - secret
users:
  # A user needs to be added for each service account.
  - "system:serviceaccount:openshift-storage:ceph-nvmeof-gateway"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ceph-nvmeof-gateway
  name: ceph-nvmeof-gateway
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ceph-nvmeof-gateway
  template:
    metadata:
      labels:
        app: ceph-nvmeof-gateway
      name: ceph-nvmeof-gateway
    spec:
      containers:
      - args:
        - -c
        - /etc/ceph/nvmeof.conf
        env:
        - name: CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
        - name: CEPH_ARGS
          value: --mon-host $(CEPH_MON_HOST) --keyring /etc/ceph/keyring
        image: quay.io/ceph/nvmeof:devel
        imagePullPolicy: IfNotPresent
        name: nvmeof-gateway
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
            drop:
            - ALL
        ports:
        - containerPort: 4420
          name: io
          protocol: TCP
        - containerPort: 5500
          name: gateway
          protocol: TCP
        - containerPort: 5499
          name: monitor
          protocol: TCP
        - containerPort: 8009
          name: discovery
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/ceph
          name: etc-ceph
      initContainers:
      - command:
        - /bin/bash
        - -c
        - |2

          set -xEeuo pipefail

          cat << EOF > /etc/ceph/ceph.conf
          [global]
          mon_host = $(CEPH_MON_HOST)
          #debug_rados = 20/5
          log_to_stderr = true

          keyring = /etc/ceph/keyring
          EOF

          cp /tmp/ceph/keyring /etc/ceph

          chmod 444 /etc/ceph/ceph.conf
          chmod 440 /etc/ceph/keyring

          cat /etc/ceph/ceph.conf

          sed "s/@@POD_NAME@@/${POD_NAME}/g;s/@@ANA_GROUP@@/${ANA_GROUP}/g;s/@@POD_IP@@/${POD_IP}/g" < /config/ceph-nvmeof.conf > /etc/ceph/nvmeof.conf
        env:
        - name: CEPH_MON_HOST
          valueFrom:
            secretKeyRef:
              key: mon_host
              name: rook-ceph-config
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ANA_GROUP
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: quay.io/ceph/ceph:v19
        imagePullPolicy: IfNotPresent
        name: generate-minimal-ceph-conf
        securityContext:
          capabilities:
            drop:
            - ALL
          privileged: true
        volumeMounts:
        - mountPath: /tmp/ceph/
          name: ceph-admin-keyring
          readOnly: true
        - mountPath: /config
          name: gateway-config
          readOnly: true
        - mountPath: /etc/ceph
          name: etc-ceph
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccount: ceph-nvmeof-gateway
      serviceAccountName: ceph-nvmeof-gateway
      volumes:
      - name: ceph-admin-keyring
        secret:
          items:
          - key: keyring
            path: keyring
            mode: 292
          secretName: rook-ceph-admin-keyring
      - name: etc-ceph
        emptyDir: {}
      - name: gateway-config
        projected:
          defaultMode: 420
          sources:
          - configMap:
              items:
              - key: config
                mode: 292
                path: ceph-nvmeof.conf
              name: ceph-nvmeof-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ceph-nvmeof-gateway
  name: ceph-nvmeof-gateway
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: io
    port: 4420
    protocol: TCP
    targetPort: 4200
  - name: gateway
    port: 5500
    protocol: TCP
    targetPort: 5500
  - name: monitor
    port: 5499
    protocol: TCP
    targetPort: 5499
  - name: discovery
    port: 8009
    protocol: TCP
    targetPort: 8009
  selector:
    app: ceph-nvmeof-gateway
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ceph-nvmeof-gateway
  name: ceph-nvmeof-config
data:
  config: |-
    # heavily based on tests/ceph-nvmeof.no-huge.conf
    # Changes are annotated with "TODO:".
    #
    #  Copyright (c) 2021 International Business Machines
    #  All rights reserved.
    #
    #  SPDX-License-Identifier: LGPL-3.0-or-later
    #
    #  Authors: anita.shekar@ibm.com, sandy.kaur@ibm.com
    #

    [gateway]
    name = @@POD_NAME@@
    group = @@ANA_GROUP@@
    addr = @@POD_IP@@
    port = 5500
    enable_auth = False
    state_update_notify = True
    state_update_timeout_in_msec = 2000
    state_update_interval_sec = 5
    enable_spdk_discovery_controller = False
    encryption_key = /etc/ceph/encryption.key
    rebalance_period_sec = 7
    max_gws_in_grp = 16
    max_ns_to_change_lb_grp = 8
    #omap_file_lock_duration = 20
    #omap_file_lock_retries = 30
    #omap_file_lock_retry_sleep_interval = 1.0
    #omap_file_update_reloads = 10
    #enable_prometheus_exporter = True
    #prometheus_exporter_ssl = True
    #prometheus_port = 10008
    #prometheus_bdev_pools = rbd
    #prometheus_stats_interval = 10
    #verify_nqns = True
    #verify_keys = True
    #verify_listener_ip = True
    #allowed_consecutive_spdk_ping_failures = 1
    #spdk_ping_interval_in_seconds = 2.0
    #max_hosts_per_namespace = 8
    #max_namespaces_with_netmask = 1000
    #max_subsystems = 128
    #max_hosts = 2048
    #max_namespaces = 2048
    #max_namespaces_per_subsystem = 256
    #max_hosts_per_subsystem = 128

    # TODO: disabled monitor client, otherwise hangs at
    # "MonitorGroup server is listening on 0.0.0.0:5499 for group id"
    enable_monitor_client = False

    [gateway-logs]
    log_level=debug
    #log_files_enabled = True
    #log_files_rotation_enabled = True
    #verbose_log_messages = True
    #max_log_file_size_in_mb=10
    #max_log_files_count=20
    #max_log_directory_backups=10
    #
    # Notice that if you change the log directory the log files will only be visible inside the container
    #
    #log_directory = /var/log/ceph/

    [discovery]
    addr = @@POD_IP@@
    port = 8009

    [ceph]
    # TODO: added "id" and updated "pool" for ODF
    id = admin
    pool = ocs-storagecluster-cephblockpool
    config_file = /etc/ceph/ceph.conf

    [mtls]
    server_key = ./server.key
    client_key = ./client.key
    server_cert = ./server.crt
    client_cert = ./client.crt

    [spdk]
    bdevs_per_cluster = 32
    mem_size=4096
    tgt_path = /usr/local/bin/nvmf_tgt
    #rpc_socket_dir = /var/tmp/
    #rpc_socket_name = spdk.sock
    #tgt_cmd_extra_args = --env-context="--no-huge -m1024" --iova-mode=va
    timeout = 60.0
    #log_level =
    #protocol_log_level = WARNING
    #log_file_dir =

    # Example value: -m 0x3 -L all
    # tgt_cmd_extra_args =

    # transports = tcp

    # Example value: {"max_queue_depth" : 16, "max_io_size" : 4194304, "io_unit_size" : 1048576, "zcopy" : false}
    transport_tcp_options = {"in_capsule_data_size" : 8192, "max_io_qpairs_per_ctrlr" : 7}

    # Example value: {"small_pool_count" : 8192, "large_pool_count" : 1024, "small_bufsize" : 8192, "large_bufsize" : 135168}
    # iobuf_options =

    # qos_timeslice_in_usecs = 0

    [monitor]
    #timeout = 1.0
    #log_file_dir =
