---
apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    app: nvmeof-cli
  name: nvmeof-cli
spec:
  containers:
  - command:
    - sh
    - -c
    - "echo '#!/bin/sh\nexec python3 -m control.cli $@' > /usr/local/bin/ceph-nvmeof && chmod +x /usr/local/bin/ceph-nvmeof && tail -f /dev/null"
    image: quay.io/ceph/nvmeof-cli:latest
    imagePullPolicy: IfNotPresent
    name: nvmeof-cli
